version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.1.0
  node: circleci/node@5.1.0

aliases:
  - image: &image
      docker:
        - image: cimg/node:18.20
  - context: &context
      context: Libmanuels

commands:
  setup:
    steps:
      - checkout
      - node/install-packages
      - pulumi/login

jobs:
  preview-staging-job:
    <<: *image
    steps:
      - setup
      - pulumi/preview:
          stack: edulib-france/dev
  preview-production-job:
    <<: *image
    steps:
      - setup
      - pulumi/preview:
          stack: edulib-france/prod
  deploy-staging-job:
    <<: *image
    steps:
      - setup
      - pulumi/update:
          stack: edulib-france/dev
  deploy-production-job:
    <<: *image
    steps:
      - setup
      - pulumi/update:
          stack: edulib-france/prod

workflows:
  dev-preview:
    jobs:
      - preview-staging-job:
          <<: *context
          filters:
            branches:
              ignore:
                - main
                - develop
  deploy-staging:
    jobs:
      - deploy-staging-job:
          <<: *context
          filters:
            branches:
              only: develop
      - preview-production-job:
          <<: *context
          filters:
            branches:
              only: develop
  deploy-production:
    jobs:
      - deploy-production-job:
          <<: *context
          filters:
            branches:
              only: main
